name: Deploy MKDocs Website
on:
  push:
    branches:
      - main
    paths:
      # only build the docs website when
      # there's a change on the .md files
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy-mkdocs-docs-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install mkdocstrings[python]

      - run: pip install mkdocs-material 

      - name: credits page generation
        run: | 
          bash << 'EOF' > docs/repo-credit.md
          echo "| File | Contributors |"
          echo "|------|--------------|"
          git ls-tree -r --name-only main ./ | while read file ; do
              contributors=$(git log --follow --pretty=format:%an -- "$file" | sort | uniq)
              joined_contributor_names="${contributors//$'\n'/,}"
              # Remove leading/trailing +
              joined_contributor_names="${joined_contributor_names#,}"
              joined_contributor_names="${joined_contributor_names%,}"
              file_without_docs="${file#docs/}"
              echo "| $file_without_docs | $joined_contributor_names |"
          done
          EOF
          
      - run: mkdocs gh-deploy --force